version: '3.4'

networks:
    backend:
    frontend:

services:
  customerdb:
    container_name: customer-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=karthik@123
    networks:
        - backend
    ports:
        - 8001:1433

  customerwebapi:
    container_name: customer-api
    image: ${DOCKER_REGISTRY-}customerwebapi
    build:
      context: .
      dockerfile: DemoMicroserviceSolution/CustomerWebApi/Dockerfile
    networks:
        - backend
    #ports:
    #    - 8002:80
    environment:
        - DB_HOST=customerdb
        - DB_NAME=dms_customer
        - DB_SA_PASSWORD=karthik@123

  productdb:
    container_name: product-db
    image: mysql:8.0.30
    environment:
        - MYSQL_ROOT_PASSWORD=password@12345#
    ports:
        - 8003:3306
    networks:
        - backend

  productwebapi:
    container_name: product-api
    image: ${DOCKER_REGISTRY-}productwebapi
    build:
      context: .
      dockerfile: DemoMicroserviceSolution/ProductWebApi/Dockerfile
    networks:
        - backend
    #ports:
    #    - 8004:80
    environment:
        - DB_HOST=productdb
        - DB_NAME=dms_product
        - DB_ROOT_PASSWORD=password@12345#
  
  orderdb:
    container_name: order-db
    image: mongo
    networks:
        - backend
    ports:
        - 8005:27017

  orderwebapi:
    container_name: order-api
    image: ${DOCKER_REGISTRY-}orderwebapi
    build:
      context: .
      dockerfile: DemoMicroserviceSolution/OrderWebApi/Dockerfile
    networks:
        - backend
    #ports:
    #    - 8006:80
    environment:
        - DB_HOST=orderdb
        - DB_NAME=dms_order

  apigateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    networks:
        - backend
        - frontend
    ports:
        - 8007:80

  blazorserverwebui:
    container_name: blazor-web-ui
    image: ${DOCKER_REGISTRY-}blazorserverwebui
    build:
      context: .
      dockerfile: BlazorServerWebUi/Dockerfile
    ports:
        - 8008:80
    networks:
        - frontend

